title: Osbern Huang
email: o.huang@griffith.edu.au
description: Academic website for Osbern Huang, Ph.D.
baseurl: ""
url: "https://[github-username].github.io/[repository-name]"
markdown: kramdown
permalink: pretty
timezone: Australia/Brisbane
sass:
  style: compressed
collections:
  pages:
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
