conference_presentations:
  - "Huang, Osbern. \"Overcoming Sampling Challenges in Hostile Environments: Asian Barometer Survey's Experience in Myanmar and China.\" WAPOR Annual Conference, Salzburg, 22-25 September 2022."
  - "Huang, Osbern. \"Liberty or equality? The neglected cultural values between inequality and democratic support.\" ECPR General Conference, Innsbruck, 22-26 August 2022."
  - "Tseng, Huan-kai, Osbern Huang, and Yu-tzung Chang. \"Text mining dimension of Chinese netizens' discourse on Taiwan.\" APSA Annual Meeting, virtual, 10-13 September 2020."
  - "Huang, Osbern. \"Big Data Analysis on the 'Taiwan Issue' in Chinese Digital Platforms: Censorship or Spin Control?\" ECPR General Conference, Wroclaw, 4-7 September 2019."
  - "Huang, Osbern, and Min-Hua Huang. \"Computer-Assisted Survey Sampling with GIS/GPS technologies.\" Australian Society for Quantitative Political Science, Canberra, 10-11 December 2018."
  - "Chang, Yu-tzung, and Osbern Huang. \"Online Public Opinion and Cross-Strait Policy: Big Data Analysis of Online Platforms in Mainland China.\" Australian Society for Quantitative Political Science, Canberra, 10-11 December 2018."
  - "Huang, Osbern, and Vienne Wang. \"Cultural Values and Support for Undemocratic Rule: A Cross-Cultural Analysis.\" IPSA World Congress of Political Science, Brisbane, 21-25 July 2018."
  - "Huang, Osbern, and Vienne Wang. \"Shaping Preferences for Redistribution: Economic Factors and Moderating Role of Traditional Cultural Values in Developing Countries.\" IPSA World Congress of Political Science, Brisbane, 21-25 July 2018."
  - "Huang, Osbern, and Yu-tzung Chang. \"Rational Choice, Confucian Values and Individual Welfare Demand: The Case of China.\" IPSA World Congress of Political Science, Poznan, 23-28 July 2016."
panel_discussant:
  - "\"The Spread of Democratic Values.\" Panel discussant with Beth Whitaker, Cynthia Kaplan, Paulina Pospieszna, and Thomas Seitz, IPSA World Congress of Political Science, Brisbane, 21-25 July 2018."
grants:
  - "Ministry of Science and Technology Postdoctoral Research Abroad Program, 2021-2022 (destination: Australian National University, Centre for Social Research & Methods)"
  - "Ministry of Science and Technology Scholarships for Humanity and Social Science Ph.D. Candidates, 2020-2021"
  - "Ministry of Science and Technology International Conference Travel Grant, 2016, 2018, 2019, and 2020"
  - "NTU College of Social Science International Conference Travel Grant, 2016, 2018, 2019, and 2020"
  - "NTU College of Social Science Ph.D. Scholarships, 2016-2017"
skills:
  languages:
    - Chinese (native)
    - English (fluent)
    - Japanese (basic)
    - French (basic)
  tools:
    - LaTeX
    - Stata
    - Matlab
    - Python
    - R
    - SAS
    - Linux
    - Bash
    - QGIS
    - C
    - SQL
    - HTML
